include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - 'plugins/**'
    - '**/*.g.dart'
  enable-experiment:
    #- non-nullable
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false


linter:
  rules:
    - camel_case_types
