include: package:pedantic/analysis_options.yaml

analyzer:
  enable-experiment:
    - non-nullable
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false


linter:
  rules:
    - camel_case_types
