name: MarkMyProgress
description: Progress recording app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.0-5.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  sembast: ^2.4.4+1

  fl_chart: ^0.10.0

  freezed_annotation: ^0.7.1
  meta: ^1.1.8

  # Functions and types
  rational: ^0.3.8
  edit_distance: ^0.4.1

  # Serialization
  json_annotation: ^3.0.1
  csv: ^4.0.3

  # Bloc
  flutter_bloc: ^4.0.0
  bloc: ^4.0.0

  # Dependency injection
  get_it: ^4.0.2

  # Native
  path: ^1.7.0
  path_provider: ^1.6.10
  path_provider_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
      ref: f1694f9dc00b3d02b2bb21913ab6f74c668885f1

  url_launcher: ^5.4.10
  url_launcher_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/url_launcher_fde
      ref: f1694f9dc00b3d02b2bb21913ab6f74c668885f1

  file_chooser:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      ref: f1694f9dc00b3d02b2bb21913ab6f74c668885f1
      path: plugins/file_chooser

  easy_localization:
    git:
      url: https://github.com/adsamcik/easy_localization.git


dev_dependencies:
  flutter_test:
    sdk: flutter


  pedantic: ^1.9.0
  intl: ^0.16.1

  # Dependency injection
  injectable_generator: ^0.4.1

  # Code generators
  freezed: ^0.10.9
  json_serializable: ^3.3.0

  # flutter pub run build_runner build (or watch)
  build_runner: ^1.10.0
  package_info: ^0.4.1

  # Used by tests. Not required to use `json_serializable`.
  build_verify: ^1.1.1
  test: ^1.14.6

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900

    - family:  AppIcons
      fonts:
         - asset: fonts/Icons.ttf

  assets:
     - assets/localization/
