name: myprogress
description: Progress recording app.
version: 2020.2.0

publish_to: 'none'

environment:
  sdk: ">=2.9.0-0.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sembast: ^2.4.7+4

  fl_chart: ^0.11.0

  freezed_annotation: ^0.11.0
  meta: ^1.2.2

  # Functions and types
  rational: ^0.3.8
  edit_distance: ^0.4.1

  # Serialization
  json_annotation: ^3.0.1
  csv: ^4.0.3

  # Bloc
  flutter_bloc: ^6.0.1
  bloc: ^6.0.1

  # Dependency injection
  get_it: ^4.0.4

  # Native
  path: ^1.7.0
  path_provider: ^1.6.11
  path_provider_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
      ref: 9e9b68b67c2a2c0b82eed2224f709aff2ccbab7c

  url_launcher: ^5.5.0
  url_launcher_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/url_launcher_fde
      ref: 9e9b68b67c2a2c0b82eed2224f709aff2ccbab7c

  file_chooser:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 9e9b68b67c2a2c0b82eed2224f709aff2ccbab7c

  easy_localization:
    git:
      url: https://github.com/adsamcik/easy_localization.git

dev_dependencies:
  flutter_test:
    sdk: flutter


  pedantic: ^1.9.2
  intl: ^0.16.1

  # Dependency injection
  injectable_generator: ^1.0.2

  # Code generators
  freezed: ^0.11.4
  json_serializable: ^3.3.0

  # flutter pub run build_runner build (or watch)
  build_runner: ^1.10.0
  package_info: ^0.4.1

  # Used by tests. Not required to use `json_serializable`.
  build_verify: ^1.1.1

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900

    - family:  AppIcons
      fonts:
        - asset: assets/fonts/Icons.ttf

  assets:
    - assets/localization/
