name: myprogress
description: Progress recording app.
version: 2020.1.1+2

publish_to: 'none'

environment:
  sdk: ">=2.9.0-14.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  sembast: ^2.4.5

  fl_chart: ^0.10.0

  freezed_annotation: ^0.11.0
  meta: ^1.1.8

  # Functions and types
  rational: ^0.3.8
  edit_distance: ^0.4.1

  # Serialization
  json_annotation: ^3.0.1
  csv: ^4.0.3

  # Bloc
  flutter_bloc: ^4.0.1
  bloc: ^4.0.0

  # Dependency injection
  get_it: ^4.0.2

  # Native
  path: ^1.7.0
  path_provider: ^1.6.11
  path_provider_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
      ref: b0794faf2c000576515aee56ca6bb5bee64cece4

  url_launcher: ^5.4.11
  url_launcher_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/url_launcher_fde
      ref: b0794faf2c000576515aee56ca6bb5bee64cece4

  file_chooser:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: b0794faf2c000576515aee56ca6bb5bee64cece4

  easy_localization:
    git:
      url: https://github.com/adsamcik/easy_localization.git


dev_dependencies:
  flutter_test:
    sdk: flutter


  pedantic: ^1.9.0
  intl: ^0.16.1

  # Dependency injection
  injectable_generator: ^0.4.1

  # Code generators
  freezed: ^0.11.2
  json_serializable: ^3.3.0

  # flutter pub run build_runner build (or watch)
  build_runner: ^1.10.0
  package_info: ^0.4.1

  # Used by tests. Not required to use `json_serializable`.
  build_verify: ^1.1.1
  test: ^1.15.1

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900

    - family:  AppIcons
      fonts:
        - asset: assets/fonts/Icons.ttf

  assets:
    - assets/localization/
