name: myprogress
description: Progress recording app.
version: 2020.2.0

publish_to: 'none'

environment:
  sdk: ">=2.10.0-0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sembast: ^2.4.9

  fl_chart: ^0.12.2

  freezed_annotation: ^0.12.0
  meta: ^1.2.4

  # Functions and types
  rational: ^0.3.8
  edit_distance: ^0.4.1

  # Serialization
  json_annotation: ^3.1.1
  csv: ^4.1.0

  # Bloc
  flutter_bloc: ^6.1.2
  bloc: ^6.1.1

  # Dependency injection
  get_it: ^5.0.6

  # Native
  path: ^1.7.0
  path_provider: ^1.6.27

  url_launcher: ^5.7.10

  file_chooser:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 040f36c82b63e8764ec2fd97066767503a667b6d

  easy_localization:
    git:
      url: https://github.com/adsamcik/easy_localization.git

dev_dependencies:
  flutter_test:
    sdk: flutter


  pedantic: ^1.9.2

  # Dependency injection
  injectable_generator: ^1.0.7

  # Code generators
  freezed: ^0.12.7
  json_serializable: ^3.5.1

  # flutter pub run build_runner build (or watch)
  build_runner: ^1.11.1
  package_info: ^0.4.3+4

  # Used by tests. Not required to use `json_serializable`.
  build_verify: ^1.1.1

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900

    - family:  AppIcons
      fonts:
        - asset: assets/fonts/Icons.ttf

  assets:
    - assets/localization/
